export const stacks = [
    [' react', 'react'],
    [' ng ', 'angular'],
    ['vite', 'vite'],
    ['quasar', 'quasar'],
    ['npx nuxi', 'nuxt'],
    ['npx create-remix', 'remix'],
    ['init video', 'remotion'],
    ['init slidev', 'slidev'],
    ['create-docusaurus', 'docusaurus'],
    ['create svelte', 'svelte'],
    ['create slidev', 'slidev'],
    ['create qwik', 'qwik'],
    ['create next-app', 'nextjs'],
    ['create astro', 'astro'],
    ['add effector', 'effector'],
    ['@11ty', 'eleventy'],

    [' wijmo', 'wijmo'],
    [' webpack', 'webpack'],
    [' webcontainer-api', 'webcontainer-api'],
    [' vue', 'vue'],
    [' vitest', 'vitest'],
    [' typescript', 'typescript'],
    [' taiga', 'taiga'],
    [' solid', 'solid'],
    [' rxjs', 'rxjs'],
    [' react-typescript', 'react-typescript'],
    [' preact', 'preact'],
    [' polymer', 'polymer'],
    [' node', 'node'],
    [' node-alt', 'node-alt'],
    [' nextjs-dark', 'nextjs-dark'],
    [' nestjs', 'nestjs'],
    [' native-script', 'native-script'],
    [' lit', 'lit'],
    [' koa', 'koa'],
    [' kendo-ui', 'kendo-ui'],
    [' javascript', 'javascript'],
    [' ionic', 'ionic'],
    [' ignite-ui', 'ignite-ui'],
    [' html5', 'html5'],
    [' greensock', 'greensock'],
    [' graphql', 'graphql'],
    [' gatsby', 'gatsby'],
    [' feathers', 'feathers'],
    [' fast-design', 'fast-design'],
    [' express', 'express'],
    [' eggjs', 'eggjs'],
    [' bootstrap', 'bootstrap'],
]